<html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1'>
<meta name='applicable-device' content='pc'><meta name='keywords' content='电脑,电脑讲解,电脑技术,编程,电脑故障维修Java，你告诉我 fail-fast 是什么鬼？' />
<script src='../../highlight/highlight.pack.js'></script>
<link rel='stylesheet' type='text/css' href='../../highlight/styles/monokai.css'/>

<link rel='stylesheet' href='../../fenxiang/dist/css/share.min.css'>
<script src='../../fenxiang/src/js/social-share.js'></script>
<script src='../../fenxiang/src/js/qrcode.js'></script>

</head><body><script>hljs.initHighlightingOnLoad();</script><script>
var system ={};  
var p = navigator.platform;       
system.win = p.indexOf('Win') == 0;  
system.mac = p.indexOf('Mac') == 0;  
system.x11 = (p == 'X11') || (p.indexOf('Linux') == 0);     
if(system.win||system.mac||system.xll){
document.write("<link href='../css/3.css' rel='stylesheet' type='text/css'>");}else{ document.write("<link href='../css/3wap.css' rel='stylesheet' type='text/css'>");}</script><script src='../../js/3.js'></script><div class='div2'><div class='heading_nav'><ul><div><li><a href='../../index.html'>首页</a></li>
</div><div onclick='hidden1()' >分享</div>
</ul></div></div>
<div id='heading_nav2'> 
<li class='row' >
<div class='social-share' data-mode='prepend'><a href='javascript:' class='social-share-icon icon-heart'></a></div></li></div><script charset='utf-8' src='../../3/js/hengfu.js'></script><script charset='utf-8' src='../../3/js/hengfu2.js'></script><hr><div class='div1'><div class='biaoti'><center>Java，你告诉我 fail-fast 是什么鬼？</center></div><div class='banquan'>原文出处:本文由博客园博主沉默王二提供。<br/>
原文连接:https://www.cnblogs.com/qing-gee/p/11909576.html</div><br>
    <p>本篇我们来聊聊 Java 的 fail-fast 机制，文字一如既往的有趣哦。</p>
<!--more-->
<h3 id="前言">01、前言</h3>
<p>说起来真特么惭愧：十年 IT 老兵，Java 菜鸟一枚。今天我才了解到 Java 还有 fail-fast 一说。不得不感慨啊，学习真的是没有止境。只要肯学，就会有巨多巨多别人眼中的“旧”知识涌现出来，并且在我这全是新的。</p>
<p>能怎么办呢？除了羞愧，就只能赶紧全身心地投入学习，把这些知识掌握。</p>
<p>为了镇楼，必须搬一段英文来解释一下 fail-fast。</p>
<blockquote>
<p>In systems design, a fail-fast system is one which immediately reports at its interface any condition that is likely to indicate a failure. Fail-fast systems are usually designed to stop normal operation rather than attempt to continue a possibly flawed process. Such designs often check the system's state at several points in an operation, so any failures can be detected early. The responsibility of a fail-fast module is detecting errors, then letting the next-highest level of the system handle them.</p>
</blockquote>
<p>大家不嫌弃的话，我就用蹩脚的英语能力翻译一下。某场战役当中，政委发现司令员在乱指挥的话，就立马报告给权限更高的中央军委——这样可以有效地避免更严重的后果出现。当然了，如果司令员是李云龙的话，报告也没啥用。</p>
<p>不过，Java 的世界里不存在李云龙。fail-fast 扮演的就是政委的角色，一旦报告给上级，后面的行动就别想执行。</p>
<p>怎么和代码关联起来呢？看下面这段代码。</p>
<pre><code><code>public void test(Wanger wanger) {   
    if (wanger == null) {
        throw new RuntimeException(&quot;wanger 不能为空&quot;);
    }
    
    System.out.println(wanger.toString());
}</code></code></pre>
<p>一旦检测到 wanger 为 null，就立马抛出异常，让调用者来决定这种情况下该怎么处理，下一步 <code>wanger.toString()</code> 就不会执行了——避免更严重的错误出现，这段代码由于太过简单，体现不出来，后面会讲到。</p>
<p>瞧，fail-fast 就是这个鬼，没什么神秘的。如果大家源码看得比较多的话，这种例子多得就像旅游高峰期的人头。</p>
<p>然后呢，没了？三秒钟，别着急，我们继续。</p>
<h3 id="for-each-中集合的-remove-操作">02、for each 中集合的 remove 操作</h3>
<p>很长一段时间里，<a href="https://mp.weixin.qq.com/s/feoOINGSyivBO8Z1gaQVOA">我</a>都不明白为什么不能在 <code>for each</code> 循环里进行元素的 remove。今天我们就来借机来体验一把。</p>
<pre><code><code>List&lt;String&gt; list = new ArrayList&lt;&gt;();
list.add(&quot;沉默王二&quot;);
list.add(&quot;沉默王三&quot;);
list.add(&quot;一个文章真特么有趣的程序员&quot;);

for (String str : list) {
    if (&quot;沉默王二&quot;.equals(str)) {
        list.remove(str);
    }
}

System.out.println(list);</code></code></pre>
<p>这段代码看起来没有任何问题，但运行起来就糟糕了。</p>
<pre><code><code>Exception in thread &quot;main&quot; java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
    at java.util.ArrayList$Itr.next(ArrayList.java:859)
    at com.cmower.java_demo.str.Cmower3.main(Cmower3.java:14)</code></code></pre>
<p>为毛呢？</p>
<h3 id="分析问题的杀手锏">03、分析问题的杀手锏</h3>
<p>这时候就只能看源码了，ArrayList.java 的 909 行代码是这样的。</p>
<pre><code><code>final void checkForComodification() {
    if (modCount != expectedModCount)
        throw new ConcurrentModificationException();
}</code></code></pre>
<p>也就是说，remove 的时候执行了 <code>checkForComodification</code> 方法，该方法对 modCount 和 expectedModCount 进行了比较，发现两者不等，就抛出了 <code>ConcurrentModificationException</code> 异常。</p>
<p>可为什么会执行 <code>checkForComodification</code> 方法呢？这就需要反编译一下 <code>for each</code> 那段代码了。</p>
<pre><code><code>List&lt;String&gt; list = new ArrayList();
list.add(&quot;沉默王二&quot;);
list.add(&quot;沉默王三&quot;);
list.add(&quot;一个文章真特么有趣的程序员&quot;);
Iterator var3 = list.iterator();

while (var3.hasNext()) {
    String str = (String) var3.next();
    if (&quot;沉默王二&quot;.equals(str)) {
        list.remove(str);
    }
}

System.out.println(list);</code></code></pre>
<p>原来 <code>for each</code> 是通过迭代器 Iterator 配合 while 循环实现的。</p>
<p>1）<code>ArrayList.iterator()</code> 返回的 Iterator 其实是 ArrayList 的一个内部类 Itr。</p>
<pre><code><code>public Iterator&lt;E&gt; iterator() {
    return new Itr();
}</code></code></pre>
<p>Itr 实现了 Iterator 接口。</p>
<pre><code><code>private class Itr implements Iterator&lt;E&gt; {
    int cursor;       // index of next element to return
    int lastRet = -1; // index of last element returned; -1 if no such
    int expectedModCount = modCount;

    Itr() {}

    public boolean hasNext() {
        return cursor != size;
    }

    @SuppressWarnings(&quot;unchecked&quot;)
    public E next() {
        checkForComodification();
        int i = cursor;
        Object[] elementData = ArrayList.this.elementData;
        if (i &gt;= elementData.length)
            throw new ConcurrentModificationException();
        cursor = i + 1;
        return (E) elementData[lastRet = i];
    }
}</code></code></pre>
<p>也就是说 <code>new Itr()</code> 的时候 expectedModCount 被赋值为 modCount，而 modCount 是 List 的一个成员变量，表示集合被修改的次数。由于 list 此前执行了 3 次 add 方法，所以 modCount 的值为 3；expectedModCount 的值也为 3。</p>
<p>可当执行 <code>list.remove(str)</code> 后，modCount 的值变成了 4。</p>
<pre><code><code>private void fastRemove(int index) {
    modCount++;
    int numMoved = size - index - 1;
    if (numMoved &gt; 0)
        System.arraycopy(elementData, index+1, elementData, index,
                         numMoved);
    elementData[--size] = null; // clear to let GC do its work
}</code></code></pre>
<p>注：remove 方法内部调用了 fastRemove 方法。</p>
<p>下一次循环执行到 <code>String str = (String) var3.next();</code> 的时候，就会调用 <code>checkForComodification</code> 方法，此时一个为 3，一个为 4，就只好抛出异常 ConcurrentModificationException 了。</p>
<p>不信，可以直接在 ArrayList 类的 909 行打个断点 debug 一下。</p>
<p><img src="./images/Java，你告诉我 fail-fast 是什么鬼？0.png" /></p>
<p>真的耶，一个是 4 一个是 3。</p>
<p><strong>总结一下</strong>。在 <code>for each</code> 循环中，集合遍历其实是通过迭代器 Iterator 配合 while 循环实现的，但是元素的 remove 却直接使用的集合类自身的方法。这就导致 Iterator 在遍历的时候，会发现元素在自己不知情的情况下被修改了，它觉得很难接受，就抛出了异常。</p>
<p>读者朋友们，你们是不是觉得我跑题了，fail-fast 和 <code>for each</code> 中集合的 remove 操作有什么关系呢？</p>
<p>有！Iterator 使用了 fail-fast 的保护机制。</p>
<h3 id="怎么避开-fail-fast-保护机制呢">04、怎么避开 fail-fast 保护机制呢</h3>
<p>通过上面的分析，相信大家都明白为什么不能在 <code>for each</code> 循环里进行元素的 remove 了。</p>
<p>那怎么避开 fail-fast 保护机制呢？毕竟删除元素是常规操作，咱不能因噎废食啊。</p>
<p>1）remove 后 break</p>
<pre><code><code>List&lt;String&gt; list = new ArrayList&lt;&gt;();
list.add(&quot;沉默王二&quot;);
list.add(&quot;沉默王三&quot;);
list.add(&quot;一个文章真特么有趣的程序员&quot;);

for (String str : list) {
    if (&quot;沉默王二&quot;.equals(str)) {
        list.remove(str);
        break;
    }
}</code></code></pre>
<p>我怎么这么聪明，忍不住骄傲一下。有读者不明白为什么吗？那我上面的源码分析可就白分析了，爬楼再看一遍吧！</p>
<p>略微透露一下原因：break 后循环就不再遍历了，意味着 Iterator 的 next 方法不再执行了，也就意味着 <code>checkForComodification</code> 方法不再执行了，所以异常也就不会抛出了。</p>
<p>但是呢，当 List 中有重复元素要删除的时候，break 就不合适了。</p>
<p>2）for 循环</p>
<pre><code><code>List&lt;String&gt; list = new ArrayList&lt;&gt;();
list.add(&quot;沉默王二&quot;);
list.add(&quot;沉默王三&quot;);
list.add(&quot;一个文章真特么有趣的程序员&quot;);
for (int i = 0, n = list.size(); i &lt; n; i++) {
    String str = list.get(i);
    if (&quot;沉默王二&quot;.equals(str)) {
        list.remove(str);
    }
}</code></code></pre>
<p>for 循环虽然可以避开 fail-fast 保护机制，也就说 remove 元素后不再抛出异常；但是呢，这段程序在原则上是有问题的。为什么呢？</p>
<p>第一次循环的时候，i 为 0，<code>list.size()</code> 为 3，当执行完 remove 方法后，i 为 1，<code>list.size()</code> 却变成了 2，因为 list 的大小在 remove 后发生了变化，也就意味着“沉默王三”这个元素被跳过了。能明白吗？</p>
<p>remove 之前 <code>list.get(1)</code> 为“沉默王三”；但 remove 之后 <code>list.get(1)</code> 变成了“一个文章真特么有趣的程序员”，而 <code>list.get(0)</code> 变成了“沉默王三”。</p>
<p>3）Iterator</p>
<pre><code><code>List&lt;String&gt; list = new ArrayList&lt;&gt;();
list.add(&quot;沉默王二&quot;);
list.add(&quot;沉默王三&quot;);
list.add(&quot;一个文章真特么有趣的程序员&quot;);

Iterator&lt;String&gt; itr = list.iterator();

while (itr.hasNext()) {
    String str = itr.next();
    if (&quot;沉默王二&quot;.equals(str)) {
        itr.remove();
    }
}</code></code></pre>
<p>为什么使用 Iterator 的 remove 方法就可以避开 fail-fast 保护机制呢？看一下 remove 的源码就明白了。</p>
<pre><code><code>public void remove() {
    if (lastRet &lt; 0)
        throw new IllegalStateException();
    checkForComodification();

    try {
        ArrayList.this.remove(lastRet);
        cursor = lastRet;
        lastRet = -1;
        expectedModCount = modCount;
    } catch (IndexOutOfBoundsException ex) {
        throw new ConcurrentModificationException();
    }
}</code></code></pre>
<p>虽然删除元素依然使用的是 ArrayList 的 remove 方法，但是删除完会执行 <code>expectedModCount = modCount</code>，保证了 expectedModCount 与 modCount 的同步。</p>
<h3 id="最后">05、最后</h3>
<p>在 Java 中，fail-fast 从狭义上讲是针对多线程情况下的集合迭代器而言的。这一点可以从 <code>ConcurrentModificationException</code> 定义上看得出来。</p>
<blockquote>
<p>This exception may be thrown by methods that have detected concurrent<br />
modification of an object when such modification is not permissible.<br><br />
For example, it is not generally permissible for one thread to modify a Collectionwhile another thread is iterating over it. In general, the results of theiteration are undefined under these circumstances. Some Iteratorimplementations (including those of all the general purpose collection implementationsprovided by the JRE) may choose to throw this exception if this behavior isdetected. Iterators that do this are known as fail-fast iterators,as they fail quickly and cleanly, rather that risking arbitrary,non-deterministic behavior at an undetermined time in the future.</p>
</blockquote>
<p>再次拙劣地翻译一下。</p>
<p>该异常可能由于检测到对象在并发情况下被修改而抛出的，而这种修改是不允许的。</p>
<p>通常，这种操作是不允许的，比如说一个线程在修改集合，而另一个线程在迭代它。这种情况下，迭代的结果是不确定的。如果检测到这种行为，一些 Iterator（比如说 ArrayList 的内部类 Itr）就会选择抛出该异常。这样的迭代器被称为 fail-fast 迭代器，因为尽早的失败比未来出现不确定的风险更好。</p>
<p>既然是针对多线程，为什么我们之前的分析都是基于单线程的呢？因为从广义上讲，fail-fast 指的是当有异常或者错误发生时就立即中断执行的这种设计，从单线程的角度去分析，大家更容易明白。</p>
<p>你说对吗？</p>
<h3 id="致谢">06、致谢</h3>
<p>谢谢大家的阅读，原创不易，喜欢就随手点个赞👍，这将是我最强的写作动力。</p>


</div><hr><script charset='utf-8' src='../../js/sming.js'></script></body></html>